# Site settings
name: Fuchs geht um
author: Katharina Fuchs
description: auf Trampelpfoten durch die Welt
email: fuchsbloggt@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://fuchsgehtum.de # the base hostname & protocol for your site

paginate: 7
paginate_path: /:num

# Build settings
permalink: /:title
markdown: kramdown
highlighter: rouge
